# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 17:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('grandmashouse', '0002_auto_20160822_1522'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('productManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
