# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grandmashouse', '0004_auto_20160823_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductToCategory', to='grandmashouse.Category'),
        ),
    ]
