# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandmashouse', '0007_auto_20160823_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
