# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('grandmashouse', '0010_auto_20160823_1640'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('orderManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='billingaddress',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='billingname',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
